--- 
- hosts: all
  become: true
  tasks:
  - name: Add apt-key for new repository
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: CA548A0A0312D8E6
  - name: Add log2ram to sources.list
    apt_repository:
      repo: deb http://packages.azlux.fr/debian/ buster main
      state: present
  - name: update pkg database
    apt:
      upgrade: yes
      update_cache: yes
  - name: Install log2ram
    apt:
      pkg:
      - log2ram

  - name: modify config
    lineinfile:
      path: /etc/log2ram.conf
      regexp: '^SIZE=(.*)$'
      line: 'SIZE=80M'
      backrefs: yes

  - name: Start log2ram service
    systemd:
      state: started
      name: log2ram
